#!/bin/sh
#
#PBS -q hotel
#PBS -N spacedishlfp_setcomp
#PBS -l nodes=1
#PBS -l walltime=150:00:00
#PBS -l mem=25gb
#PBS -o spacedishlfp_setcomp.o
#PBS -e spacedishlfp_setcomp.e
#PBS -V
#PBS -M rigao@ucsd.edu
#PBS -m ae
cd ~
/opt/matlab/2015a/bin/matlab -singleCompThread -nodesktop -nojvm -r rg_spacedishlfp_setcomp

# get out of here
exit
